// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(grunt) {
    var Remarkable;
    Remarkable = require('remarkable');
    return grunt.registerMultiTask('remarkable', 'Run remarkable on files', function(target) {
      var options, remarkable;
      options = this.options({});
      remarkable = new Remarkable(options);
      return this.files.forEach(function(f) {
        var src;
        src = f.src.filter(function(path) {
          if (!grunt.file.exists(path)) {
            grunt.log.warn("Source file " + path + " doesn't exist");
            false;
          }
          return true;
        });
        return src.map(function(path) {
          var out;
          if (grunt.file.isDir(path)) {
            return;
          }
          out = remarkable.render(grunt.file.read(path));
          grunt.file.write(f.dest, out);
          return grunt.verbose.write("File " + f.dest + " created");
        });
      });
    });
  };

}).call(this);
